kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  annotations:
      dummy: "test"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

